name: SonarQube

on: [push, pull_request]

permissions:
  pull-requests: write
  metadata: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Cache SonarQube packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar

    - name: Install SonarQube Scanner
      run: |
        curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
        unzip sonar-scanner-cli.zip
        export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin

    - name: Run SonarQube Scanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.projectKey=prova \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.bb8e39b479835eaedaf988bb70533262b626f791 }}
