name: Example Workflow

on: [push, pull_request]

permissions:
  pull-requests: write
  metadata: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run a script
      run: echo "Hello, world!"
